// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"sc_gateway/internal/conf"
	"sc_gateway/internal/server"
	"sc_gateway/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, data *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	healthService := service.NewHealthService()
	grpcServer := server.NewGRPCServer(confServer, healthService, logger)
	httpServer := server.NewHTTPServer(confServer, healthService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
	}, nil
}
