// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0
// source: skycontrol/viability/health.proto

package viability

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Viability_Health_FullMethodName = "/helloworld.v1.Viability/Health"
)

// ViabilityClient is the client API for Viability service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ViabilityClient interface {
	Health(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*HealthReply, error)
}

type viabilityClient struct {
	cc grpc.ClientConnInterface
}

func NewViabilityClient(cc grpc.ClientConnInterface) ViabilityClient {
	return &viabilityClient{cc}
}

func (c *viabilityClient) Health(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*HealthReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthReply)
	err := c.cc.Invoke(ctx, Viability_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ViabilityServer is the server API for Viability service.
// All implementations must embed UnimplementedViabilityServer
// for forward compatibility.
type ViabilityServer interface {
	Health(context.Context, *emptypb.Empty) (*HealthReply, error)
	mustEmbedUnimplementedViabilityServer()
}

// UnimplementedViabilityServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedViabilityServer struct{}

func (UnimplementedViabilityServer) Health(context.Context, *emptypb.Empty) (*HealthReply, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedViabilityServer) mustEmbedUnimplementedViabilityServer() {}
func (UnimplementedViabilityServer) testEmbeddedByValue()                   {}

// UnsafeViabilityServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ViabilityServer will
// result in compilation errors.
type UnsafeViabilityServer interface {
	mustEmbedUnimplementedViabilityServer()
}

func RegisterViabilityServer(s grpc.ServiceRegistrar, srv ViabilityServer) {
	// If the following call panics, it indicates UnimplementedViabilityServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Viability_ServiceDesc, srv)
}

func _Viability_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ViabilityServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Viability_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ViabilityServer).Health(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// Viability_ServiceDesc is the grpc.ServiceDesc for Viability service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Viability_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "helloworld.v1.Viability",
	HandlerType: (*ViabilityServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Health",
			Handler:    _Viability_Health_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "skycontrol/viability/health.proto",
}
